version: '3'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    container_name: customer_experience-db
    image: amazon/dynamodb-local:1.17.2
    restart: always
    ports:
      - "8001:8000"
    networks:
      - lambda-local
networks:
  lambda-local:
    external: true
    