@baseURL = http://127.0.0.1:3000/company
@baseURL = https://api.zero-reais-lab.cloud/v1/customer-experience/company

@company = pizzaria-del-vitiente

### @name getFoodMenu
GET {{baseURL}}/{{company}}
Content-Type: application/json