@baseURL = https://api.zero-reais-lab.cloud/v1/customer-experience/favorites
@baseURL = http://127.0.0.1:3000/favorites

### LOCAL TOKEN
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAxNjU4MTAsImp0aSI6ImpvaG4xQGRvZS5jb20iLCJzdWIiOiI5MjExNTZkYy00OTE5LTRiNjctYmI5Ny1iZGE5Y2FkZTBlY2YifQ.L8qOe2xL-7NnQM5VKmBVe01oVggZcX7MIz7CoBlwJlM
### PROD TOKEN
# @authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDk3MTMwODQsImp0aSI6ImpvaG4xQGRvZS5jb20iLCJzdWIiOiI5MjExNTZkYy00OTE5LTRiNjctYmI5Ny1iZGE5Y2FkZTBlY2YifQ.EhnFlwPLYnVEQ8xdpIKdwxeVnfiQTgPkwF8Kf7HA4jw

@mealID = 1
@favoriteID = 1

### @name addFavorite
POST {{baseURL}}
Content-Type: application/json
Cookie: usess={{authToken}};

{
  "meal": {{mealID}}
}

### @name removeFavorite
DELETE {{baseURL}}/{{favoriteID}}
Content-Type: application/json
Cookie: usess={{authToken}};

### @name listMyFavorites
GET {{baseURL}}
Content-Type: application/json
Cookie: usess={{authToken}};