@baseURL = https://api.zero-reais-lab.cloud/v1/customer-experience/favorites
@baseURL = http://127.0.0.1:3000/favorites

### LOCAL TOKEN
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAxNjU4MTAsImp0aSI6ImpvaG4xQGRvZS5jb20iLCJzdWIiOiI5MjExNTZkYy00OTE5LTRiNjctYmI5Ny1iZGE5Y2FkZTBlY2YifQ.L8qOe2xL-7NnQM5VKmBVe01oVggZcX7MIz7CoBlwJlM
### PROD TOKEN
# @authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDk3MTMwODQsImp0aSI6ImpvaG4xQGRvZS5jb20iLCJzdWIiOiI5MjExNTZkYy00OTE5LTRiNjctYmI5Ny1iZGE5Y2FkZTBlY2YifQ.EhnFlwPLYnVEQ8xdpIKdwxeVnfiQTgPkwF8Kf7HA4jw

# @mealID = bb73b635-921f-43a0-a2ea-5430744caaae
@mealID = a12d8a5e-8e46-4402-84d5-45349acb3230

###
# @name addFavorite
POST {{baseURL}}
Content-Type: application/json
Cookie: usess={{authToken}};

{
  "meal": "{{mealID}}"
}

###
# @name listMyFavorites
GET {{baseURL}} HTTP/2
Content-Type: application/json
Cookie: usess={{authToken}};

###
# @name removeFavorite
DELETE {{baseURL}}/{{listMyFavorites.response.body.data[0].id}}
Content-Type: application/json
Cookie: usess={{authToken}};