@baseURL = http://127.0.0.1:3000/session
@baseURL = https://api.zero-reais-lab.cloud/v1/customer-experience

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDk3MDc0MTMsImp0aSI6ImpvaG4xQGRvZS5jb20iLCJzdWIiOiI5MjExNTZkYy00OTE5LTRiNjctYmI5Ny1iZGE5Y2FkZTBlY2YifQ.ddvN7Hn1wAtEJpByHIlJeGl633Om64ZbMvfmPweXIzQ

### @name signIn
POST {{baseURL}}/sign-in

{
	"email": "john1@doe.com",
	"password": "123456"
}

### @name signOut
POST {{baseURL}}/sign-out
Cookie: usess={{authToken}}

### @name recoverPassword
POST {{baseURL}}/recover-password

{
	"email": "john1@doe.com"
}

### @name resetPassword
POST {{baseURL}}/reset-password

{
	"otp": 299814,
	"password": "123456",
	"confirm_password": "123456"
}