GET http://127.0.0.1:3000/user
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDkxMzE2MTIsImp0aSI6ImpvaG5AZG9lLmNvbSIsInN1YiI6ImFhZGQ0M2E3LTZlNzAtNDMzOS1hY2Y4LTc3MDQyOTNmMzJlYyJ9.WVHU-T2sI7KNMiBWBGf6fOE1qMGBckmrKfyljLE--FI
Cookie: usess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDkxMzE2MTIsImp0aSI6ImpvaG5AZG9lLmNvbSIsInN1YiI6ImFhZGQ0M2E3LTZlNzAtNDMzOS1hY2Y4LTc3MDQyOTNmMzJlYyJ9.WVHU-T2sI7KNMiBWBGf6fOE1qMGBckmrKfyljLE--FI;

###
POST http://127.0.0.1:3000/user
Content-Type: application/json

{
	"name": "John",
	"lastname": "Doe",
	"email": "john@doe.com",
	"phone": "+5562982622387",
	"password": "123456",
	"confirm_password": "123456",
	"avatar": "https://randomuser.me/api/portraits/men/24.jpg"
}

###