GET http://127.0.0.1:3000/user
Content-Type: application/json
Cookie: usess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDkyMTUzODIsImp0aSI6ImpvaG5AZG9lLmNvbSIsInN1YiI6ImNkMzA1NTE2LTlmMzUtNDYxYy04YWY0LTZmOGE1MzI3ODM5OCJ9.Q4TxZRWPWAguVF_GANio9sYjqoeOjWuKzfoIg8m8CXE;

###
POST http://127.0.0.1:3000/user
Content-Type: application/json

{
	"name": "John",
	"lastname": "Doe",
	"email": "john@doe.com",
	"phone": "+5562982622387",
	"password": "123456",
	"confirm_password": "123456",
	"avatar": "https://randomuser.me/api/portraits/men/24.jpg"
}

###
PUT http://127.0.0.1:3000/user
Content-Type: application/json
Cookie: usess=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDkyMTUzODIsImp0aSI6ImpvaG5AZG9lLmNvbSIsInN1YiI6ImNkMzA1NTE2LTlmMzUtNDYxYy04YWY0LTZmOGE1MzI3ODM5OCJ9.Q4TxZRWPWAguVF_GANio9sYjqoeOjWuKzfoIg8m8CXE;

{
	"name": "Johnny",
	"password": "123456",
	"confirm_password": "123456",
	"new_password": "123456",
	"confirm_new_password": "123456"
}

###
