AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user
  
  Sample SAM Template for user

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  UserEvent: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Key"
          AttributeType: "S"
        - 
          AttributeName: "EventID"
          AttributeType: "N"
        - 
          AttributeName: "EventType"
          AttributeType: "S"
        - 
          AttributeName: "Data"
          AttributeType: "B"
        - 
          AttributeName: "Timestamp"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "Key"
          KeyType: "HASH"
        - 
          AttributeName: "EventID"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "UserEvent"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "EventTypeIndex"
          KeySchema: 
            - 
              AttributeName: "EventType"
              KeyType: "HASH"
            - 
              AttributeName: "EventID"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - 
          IndexName: "TimestampIndex"
          KeySchema: 
            - 
              AttributeName: "Key"
              KeyType: "HASH"
            - 
              AttributeName: "Timestamp"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  UserModel: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "ID"
          AttributeType: "S"
        - 
          AttributeName: "Email"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "ID"
          KeyType: "HASH"
        - 
          AttributeName: "Email"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "UserModel"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "EmailIndex"
          KeySchema: 
            - 
              AttributeName: "Email"
              KeyType: "HASH"
            - 
              AttributeName: "ID"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  UserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user/
      Handler: user
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        HttpApiEvent:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
          TableName: !Ref UserModel
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
